name: build and deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Deploy
        run: |
          bash scripts/build.sh
          bash scripts/deploy.sh
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCP_IMAGE: ${{ secrets.GCP_IMAGE }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_SERVICE: ${{ secrets.GCP_SERVICE }}

